# Generated by Django 4.1.7 on 2023-03-23 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_challenge_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
