# Generated by Django 4.1.7 on 2023-03-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_challenge_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='sport_type',
            field=models.CharField(choices=[('Ride', 'RIDE'), ('Run', 'RUN'), ('Swim', 'SWIM'), ('Hike', 'HIKE'), ('Walk', 'WALK'), ('Alpine Ski', 'ALPINE_SKI'), ('Backcountry Ski', 'BACKCOUNTRY_SKI'), ('Canoeing', 'CANOEING'), ('Crossfit', 'CROSSFIT'), ('EBike Ride', 'EBIKE_RIDE'), ('Elliptical', 'ELLIPTICAL'), ('Ice Skate', 'ICE_SKATE'), ('Inline Skate', 'INLINE_SKATE'), ('Kayaking', 'KAYAKING'), ('Kitesurf', 'KITESURF'), ('Nordic Ski', 'NORDIC_SKI'), ('Rock Climbing', 'ROCK_CLIMBING'), ('Roller Ski', 'ROLLER_SKI'), ('Rowing', 'ROWING'), ('Snowboard', 'SNOWBOARD'), ('Snowshoe', 'SNOWSHOE'), ('Stair Stepper', 'STAIR_STEPPER'), ('Stand-Up Paddling', 'STAND_UP_PADDLING'), ('Surfing', 'SURFING'), ('Virtual Ride', 'VIRTUAL_RIDE'), ('Weight Training', 'WEIGHT_TRAINING'), ('Windsurf', 'WINDSURF'), ('Workout', 'WORKOUT'), ('Yoga', 'YOGA')], max_length=255),
        ),
    ]
