# Generated by Django 4.1.7 on 2023-03-24 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_activity_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='challenges', to='App.activity'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
