# Generated by Django 4.1.7 on 2023-03-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_challenge_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('Distance', 'DISTANCE'), ('Time', 'TIME')], default='time', max_length=255),
            preserve_default=False,
        ),
    ]
