from enum import Enum

class SportType(Enum):
    RIDE = 'Ride'
    RUN = 'Run'
    SWIM = 'Swim'
    HIKE = 'Hike'
    WALK = 'Walk'
    ALPINE_SKI = 'Alpine Ski'
    BACKCOUNTRY_SKI = 'Backcountry Ski'
    CANOEING = 'Canoeing'
    CROSSFIT = 'Crossfit'
    EBIKE_RIDE = 'EBike Ride'
    ELLIPTICAL = 'Elliptical'
    ICE_SKATE = 'Ice Skate'
    INLINE_SKATE = 'Inline Skate'
    KAYAKING = 'Kayaking'
    KITESURF = 'Kitesurf'
    NORDIC_SKI = 'Nordic Ski'
    ROCK_CLIMBING = 'Rock Climbing'
    ROLLER_SKI = 'Roller Ski'
    ROWING = 'Rowing'
    SNOWBOARD = 'Snowboard'
    SNOWSHOE = 'Snowshoe'
    STAIR_STEPPER = 'Stair Stepper'
    STAND_UP_PADDLING = 'Stand-Up Paddling'
    SURFING = 'Surfing'
    VIRTUAL_RIDE = 'Virtual Ride'
    WEIGHT_TRAINING = 'Weight Training'
    WINDSURF = 'Windsurf'
    WORKOUT = 'Workout'
    YOGA = 'Yoga'